@startuml
package "commands" {
    class CommandDispatcher {
        +addCommand(name : String, handler : CommandHandler) : void
        +processCommand(line : String) : void

    }

    interface CommandHandler {
        +runCommand(tokens : Iterator<String>) : void
    }

    class EchoCommandHandler {
        +runCommand(tokens : Iterator<String>) : void
    }

    class ExitCommandHandler {
        +runCommand(tokens : Iterator<String>) : void
    }

    class HelpCommandHandler {
        +runCommand(tokens : Iterator<String>) : void
    }

    class ProdCommandHandler {
        +runCommand(tokens : Iterator<String>) : void
        -listCommand(tokens : Iterator<String>) : void
        -addCommand(tokens : Iterator<String>) : void
        -removeCommand(tokens : Iterator<String>) : void
        -showCommand(tokens : Iterator<String>) : void
        -importCommand(tokens : Iterator<String>) : void
    }

    class TicketCommandHandler {
        +runCommand(tokens : Iterator<String>) : void
        -printTicketCommand(tokens : Iterator<String>) : void
        -removeTicketCommand(tokens : Iterator<String>) : void
        -addTicketCommand(tokens : Iterator<String>) : void
        -newTickedCommand(tokens : Iterator<String>) : void
    }

    class Converter {
        +stringToInt(s : String) : OptionalInt
        +stringToDouble(s : String) : OptionalDouble
        +stringToCategory(s : String) : Optional<Category>
    }
}

class App {
    -menu : boolean
    +main(args : String[]) : void
    +exitMenu() : void
}

package "models" {
    class Ticket {
        -MAX_PRODUCTS : int
        +addProduct(productId : int, quantity : int) : boolean
        +removeProductById(id : int) : boolean
        +toString() : String
        -totalUnits() : int
        -countCategory() : Map<Category, Integer>
        -perItemDiscount(p : Product, counts : Map<Category, Integer>) : double
        -round1(v : double) : double
        -totalPrice() : double
        -discountPrice() : double
    }

    enum Category {
        MERCH
        STATIONARY
        CLOTHES
        BOOK
        ELECTRONICS
        -discount : double
        +getDiscount() : double
    }

    class Product {
        -id : int
        -name : String
        -price : double
        +getId() : int
        +getName() : String
        +getPrice() : double
        +toString() : String
    }

    class ProductUnit {
            -category : Category
            +getCategory() : Category
    }
    
    class PersonalizableProduct {
        -texts : List<String>
    }

    class ProductService {
        -MAX_PARTICIPANT : int
        -expirationDate : Date
        #checkDate(date : Date) : boolean
    }

    class Catering {
           -PLANING_TIME : Date
            #checkDate(date : Date) : boolean
    }

    class Reunion {
        -PLANING_TIME : Date
        #checkDate(date : Date) : boolean
    }

    class User {
        -name : String
        -DNI : String
        -email : String
        -id : String

        #checkEmail(email : String) : boolean
    }
    class Client {
        #checkEmail(email : String) : boolean
    }
    class Cashier {
        #checkEmail(email : String) : boolean
    }


}

package "managers" {
    class AbstractManager<T, K> {
        +add(T : element) : void
        #add(T : element, K id) : void
        +remove(K : id) : void
        +get(K : id) : Optional<T>
        +existId(K : id) : boolean
        #getSize() : int
    }

    class ProductManager<Product, Integer> {
    }

    class ClientManager<Client, String> {
    }

    class CashierManager<Cashier, String> {
    }

    class TicketManager<Ticket, String> {
    }
}

package "factory" {
    class ProductFactory {
            +createProduct(int : id, String : name, Category : category, double : price) : Product
            +isNameValid(String : name) : boolean
            +isPriceValid(v : double) : boolean
    }

    class ClientFactory {
        +createClient(String : name, String : DNI, String : email, Cashier : cashierWhoRegisters) : Client
    }

    class CashierFactory {
        +createCashier(String : name, String : email, String : id) : Cashier
        +createCashier(String name, String email) : Cashier
        -createID() : String
    }

    class TicketFactory {
    }
}

CommandHandler <|.. EchoCommandHandler
CommandHandler <|.. ExitCommandHandler
CommandHandler <|.. HelpCommandHandler
CommandHandler <|.. ProdCommandHandler
CommandHandler <|.. TicketCommandHandler

AbstractManager <|-- ProductManager
AbstractManager <|-- ClientManager
AbstractManager <|-- CashierManager
AbstractManager <|-- TicketManager

ProdCommandHandler ..> Converter
ProdCommandHandler ..> Product
TicketCommandHandler ..> Converter
TicketCommandHandler ..> Ticket
TicketCommandHandler ..> Product

CommandDispatcher "0" o-- "*" CommandHandler

App "1" *-- "1" CommandDispatcher
App "1" *-- "1" EchoCommandHandler
App "1" *-- "1" HelpCommandHandler
App "1" *-- "1" ExitCommandHandler
App "1" *-- "1" ProdCommandHandler
App "1" *-- "1" TicketCommandHandler

App "1" *-- "1" "managers"
App "1" *-- "1" "factory"

ProductManager --> ProductFactory
ClientManager --> ClientFactory
CashierManager --> CashierFactory
TicketManager --> TicketFactory

Product <.. ProductFactory : create
Client <.. ClientFactory : create
Cashier <.. CashierFactory : create
Ticket <.. TicketFactory : create

ProductManager "0" o-- "*" Product
ClientManager "0" o-- "*" Client
CashierManager "0" o-- "*" Cashier
TicketManager "0" o-- "*" Ticket

ProdCommandHandler --> ProductManager
ProdCommandHandler --> ProductFactory

TicketCommandHandler --> TicketManager
TicketCommandHandler --> ProductManager
TicketCommandHandler --> TicketFactory

Ticket "0" o-- "*" Product

Client <|-- User
Cashier <|-- User

ProductService <|-- Product
ProductUnit <|-- Product
PersonalizableProduct <|-- ProductUnit
Catering <|-- ProductService
Reunion <|-- ProductService
@enduml