@startuml Ticket Management System

package "commands" {
    class CommandTokens {
    - tokens: List<String>
    + next(): String
    + nextInt(): int
    + nextDouble(): double
    + nextAsIntegerId(ProductManager, boolean, String, String): Integer
    + nextCategory(): Category
    + nextDate(): LocalDateTime
    + hasNext(): boolean
    + hasNextInt(): boolean
    + hasNextDouble(): boolean
    + hasNextCategory(): boolean
    + hasNextDate(): boolean
    + getRemainingTokens(): int
    }

    class CommandDispatcher {
      - commands: Map<String, CommandHandler>
      + addCommand(String, CommandHandler)
      + processCommand(CommandTokens)
    }

package "handlers" {
  interface CommandHandler {
    + runCommand(CommandTokens tokens)
  }

  class ProdCommandHandler {
        - productCommandDispatcher: CommandDispatcher
        + runCommand(CommandTokens)
      }

      class ProdAddCommandHandler {
        - productManager: ProductManager
        + runCommand(CommandTokens)
      }

      class ProdListCommandHandler {
        - productManager: ProductManager
        + runCommand(CommandTokens)
      }

      class ProdRemoveCommandHandler {
        - productManager: ProductManager
        + runCommand(CommandTokens)
      }

      class ProdUpdateCommandHnadler {
        - productManager: ProductManager
        + runCommand(CommandTokens)
      }

      class ProdAddFoodCommandHandler {
        - productManager: ProductManager
        + runCommand(CommandTokens)
      }

      class ProdAddMeetingCommandHandler {
        - productManager: ProductManager
        + runCommand(CommandTokens)
      }

      class CashierCommandHandler {
        - cashierCommandDispatcher: CommandDispatcher
        + runCommand(CommandTokens)
      }

      class CashierAddCommandHandler {
        - cashierManager: CashierManager
        + runCommand(CommandTokens)
      }

      class CashierRemoveCommandHandler {
        - cashierManager: CashierManager
        - ticketManager: TicketManager
        + runCommand(CommandTokens)
      }

      class CashierListCommandHandler {
        - cashierManager: CashierManager
        + runCommand(CommandTokens)
      }

      class CashierShowTicketCommandHandler {
        - cashierManager: CashierManager
        + runCommand(CommandTokens)
      }

      class ClientCommandHandler {
        - ticketCommandDispatcher: CommandDispatcher
        + runCommand(CommandTokens)
      }

      class ClientAddCommandHandler {
        - clientManager: ClientManager
        - cashierManager: CashierManager
        + runCommand(CommandTokens)
      }

      class ClientRemoveCommandHandler {
        - clientManager: ClientManager
        + runCommand(CommandTokens)
      }

      class ClientListCommandHandler {
        - clientManager: ClientManager
        + runCommand(CommandTokens)
      }

      class TicketCommandHandler {
        - ticketCommandDispatcher: CommandDispatcher
        + runCommand(CommandTokens)
      }

      class TicketNewCommandHandler {
        - ticketManager: TicketManager
        - cashierManager: CashierManager
        - clientManager: ClientManager
        + runCommand(CommandTokens)
      }

      class TicketAddCommandHandler {
        - ticketManager: TicketManager
        - productManager: ProductManager
        - cashierManager: CashierManager
        + runCommand(CommandTokens)
      }

      class TicketRemoveCommandHandler {
        - ticketManager: TicketManager
        - productManager: ProductManager
        - cashierManager: CashierManager
        + runCommand(CommandTokens)
      }

      class TicketPrintCommandHandler {
        - ticketManager: TicketManager
        - cashierManager: CashierManager
        + runCommand(CommandTokens)
      }

      class TicketListCommandHandler {
        - ticketManager: TicketManager
        + runCommand(CommandTokens)
      }

      class ExitCommandHandler {
        + runCommand(CommandTokens)
      }

      class HelpCommandHandler {
        + runCommand(CommandTokens)
      }

      class EchoCommandHandler {
        + runCommand(CommandTokens)
      }
    }
}

package managers {
  abstract class AbstractManager<T, K> {
    - elements: Map<K, T>
    + add(T, K)
    + remove(K): T
    + get(K): T
    + getAll(): List<T>
    + existId(K): boolean
    + getSize(): int
  }

  class ProductManager {
    - MAX_PRODUCTS: int
    - MAX_NAME_LENGTH: int
    + addProduct(int, String, Category, double): Product
    + addCustomizableProduct(int, String, Category, double, int): Product
    + addFoodProduct(int, String, double, LocalDateTime, int): Product
    + addMeetingProduct(int, String, double, LocalDateTime, int): Product
    + isNameValid(String): boolean
    + isPriceValid(double): boolean
    + isProductListFull(): boolean
  }

  class CashierManager {
    - CASHIER_ID_LENGTH: int
    - CASHIER_EMAIL_REGEX: Pattern
    + addCashier(String, String, String): Cashier
    + addCashier(String, String): Cashier
    + removeCashierAndTickets(String, TicketManager): boolean
    + checkId(String): boolean
    - createID(): String
  }

  class ClientManager {
    - EMAIL_PATTERN: Pattern
    - DNI_PATTERN: Pattern
    - NIE_PATTERN: Pattern
    - cashierManager: CashierManager
    + addClient(String, String, String, String): Client
    + checkDNI(String): boolean
    + checkEmail(String): boolean
  }

  class TicketManager {
    - TICKET_ID_LENGTH: int
    - clientManager: ClientManager
    - cashierManager: CashierManager
    + addTicket(int): Ticket
    + addTicket(): Ticket
    + checkId(int): boolean
    - createNewId(): int
  }
}

package models {
package products {
  abstract class Product {
    - id: int
    - name: String
    - price: double
    + getId(): int
    + getName(): String
    + setName(String)
    + getPrice(): double
    + setPrice(double)
  }

  class UnitProduct {
    - category: Category
    + getCategory(): Category
    + setCategory(Category)
  }

  class PersonalizableProduct {
    - maxPers: int
    + getMaxPers(): int
  }

  abstract class ProductService {
    - maxParticipant: int
    - expirationDate: LocalDateTime
    - personasApuntadas: int
    + getExpirationDate(): LocalDateTime
    + getPersonasApuntadas(): int
    + setPersonasApuntadas(int)
    + checkTime(): boolean
    + printTicketWithPeople(): String
  }

  class Catering {
    + checkTime(): boolean
  }

  class Meeting {
    + checkTime(): boolean
  }

  enum Category {
    MERCH
    STATIONARY
    CLOTHES
    BOOK
    ELECTRONICS
    + getDiscount(): double
  }
  }

  package "users" {
    abstract class AbstractUser {
      - name: String
      - email: String
      - id: String
      + getName(): String
      + getId(): String
      + getEmail(): String
    }

    class Cashier {
      - tickets: List<Ticket>
      + getTickets(): List<Ticket>
      + addTicket(Ticket)
    }

    class Client {
      - cashierWhoRegisters: Cashier
      - tickets: List<Ticket>
      + getCashier(): Cashier
      + addTicket(Ticket)
    }
  }

   class Ticket {
        - id: int
        - initialDate: Date
        - finalDate: Date
        - ticketState: TicketState
        - items: List<TicketLine>
        + getId(): int
        + getState(): TicketState
        + getInitialDate(): Date
        + getFormattedId(): String
        + addProduct(Product, int): boolean
        + addProduct(PersonalizableProduct, int, String[]): boolean
        + removeProduct(Product)
        + closeTicket()
        + printTicket(): String
        + areAllServiceProductsValid(): boolean
      }
}

class App {
    - menu: boolean
    - dispatcher: CommandDispatcher
    - productManager: ProductManager
    - cashierManager: CashierManager
    - clientManager: ClientManager
    - ticketManager: TicketManager
    + main(String[])
    + exitMenu()
}
CommandDispatcher o-- "0..*" CommandHandler : contains

CashierCommandHandler *-- CashierAddCommandHandler
CashierCommandHandler *-- CashierListCommandHandler
CashierCommandHandler *-- CashierRemoveCommandHandler
CashierCommandHandler *-- CashierShowTicketCommandHandler

ClientCommandHandler *-- ClientAddCommandHandler
ClientCommandHandler *-- ClientListCommandHandler
ClientCommandHandler *-- ClientRemoveCommandHandler

ProdCommandHandler *-- ProdAddCommandHandler
ProdCommandHandler *-- ProdAddFoodCommandHandler
ProdCommandHandler *-- ProdAddMeetingCommandHandler
ProdCommandHandler *-- ProdListCommandHandler
ProdCommandHandler *-- ProdRemoveCommandHandler
ProdCommandHandler *-- ProdUpdateCommandHnadler

TicketCommandHandler *-- TicketNewCommandHandler
TicketCommandHandler *-- TicketAddCommandHandler
TicketCommandHandler *-- TicketRemoveCommandHandler
TicketCommandHandler *-- TicketPrintCommandHandler
TicketCommandHandler *-- TicketListCommandHandler

CommandHandler <|-- EchoCommandHandler
CommandHandler <|-- ExitCommandHandler
CommandHandler <|-- HelpCommandHandler

CommandHandler <|-- CashierCommandHandler
CommandHandler <|-- CashierAddCommandHandler
CommandHandler <|-- CashierListCommandHandler
CommandHandler <|-- CashierRemoveCommandHandler
CommandHandler <|-- CashierShowTicketCommandHandler

CommandHandler <|-- ClientCommandHandler
CommandHandler <|-- ClientAddCommandHandler
CommandHandler <|-- ClientListCommandHandler
CommandHandler <|-- ClientRemoveCommandHandler

CommandHandler <|-- ProdCommandHandler
CommandHandler <|-- ProdAddCommandHandler
CommandHandler <|-- ProdAddFoodCommandHandler
CommandHandler <|-- ProdAddMeetingCommandHandler
CommandHandler <|-- ProdListCommandHandler
CommandHandler <|-- ProdRemoveCommandHandler
CommandHandler <|-- ProdUpdateCommandHnadler

CommandHandler <|-- TicketCommandHandler
CommandHandler <|-- TicketNewCommandHandler
CommandHandler <|-- TicketAddCommandHandler
CommandHandler <|-- TicketRemoveCommandHandler
CommandHandler <|-- TicketPrintCommandHandler
CommandHandler <|-- TicketListCommandHandler

CommandDispatcher ..> CommandTokens
CommandHandler ..> CommandTokens

models ..> handlers

CommandTokens ..> Category

AbstractManager <|-- ProductManager
AbstractManager <|-- ClientManager
AbstractManager <|-- TicketManager
AbstractManager <|-- CashierManager

Product <|-- UnitProduct
Product <|-- ProductService
ProductService <|-- Catering
ProductService <|-- Meeting
UnitProduct <|-- PersonalizableProduct

ProductManager o-- Product
CashierManager o-- Cashier
ClientManager o-- Client
TicketManager o-- Ticket

Ticket *-- Product : contains
Cashier --> "0..*" Ticket : tickets
Client --> "0..*" Ticket : tickets
Client --> Cashier : registeredBy

TicketManager ..> ClientManager
TicketManager ..> CashierManager
CashierManager ..> TicketManager

App ..> CommandDispatcher
App ..> ProductManager
App ..> CashierManager
App ..> ClientManager
App ..> TicketManager

@enduml